---

elasticsearch:
  hosts:
    el-instance:
      ansible_host: 54.191.188.181
      ansible_connection: ssh
      ansible_user: ubuntu
kibana:
  hosts:
    k-instance:
      ansible_host: 34.220.31.60
      ansible_connection: ssh
      ansible_user: ubuntu
filebeat:
  hosts:
    f-instance:
      ansible_host: 34.208.29.11
      ansible_connection: ssh
      ansible_user: ubuntu
