---
all:
  hosts:
    el-instance:
      ansible_host: 34.220.64.197
    k-instance:
      ansible_host: 34.221.30.222
    f-instance:
      ansible_host: 34.219.219.134
    log-instance:
      ansible_host: 34.220.64.197  
  vars:
    ansible_connection: ssh
    ansible_user: ubuntu
elasticsearch:
  hosts:
    el-instance:
kibana:
  hosts:
    k-instance:
logstash:
  hosts:
    log-instance:    
filebeat:
  hosts:
    f-instance:                  
